import { extraEn, extraTr, extraId } from './panel-extra-messages'
import enJson from '../locales/en.json'
import trJson from '../locales/tr.json'
import idJson from '../locales/id.json'

const deepMerge = (base, override) => {
  if (Array.isArray(base) || Array.isArray(override)) {
    return override ?? base
  }
  if (base && typeof base === 'object' && override && typeof override === 'object') {
    const merged = { ...base }
    for (const key of Object.keys(override)) {
      merged[key] = key in base ? deepMerge(base[key], override[key]) : override[key]
    }
    return merged
  }
  return override ?? base
}

const baseEn = {
  menu: {
    dashboard: 'Dashboard', websites: 'Websites', packages: 'Packages', users: 'Users', databases: 'Databases', emails: 'Emails', dns: 'DNS Management', security: 'Security', docker: 'Docker', docker_manager: 'Docker Manager', docker_apps: 'Docker Apps', cloudflare: 'CloudFlare', filemanager: 'File Manager', php: 'PHP Management', server_status: 'Server Status', reseller: 'Reseller Management'
  },
  common: {
    save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', create: 'Create', add: 'Add', confirm_delete: 'Are you sure you want to delete this?', loading: 'Loading...', error: 'An error occurred', success: 'Operation successful', search: 'Search...', actions: 'Actions', status: 'Status', active: 'Active', inactive: 'Inactive', name: 'Name', email: 'Email', password: 'Password', no_data: 'No records found', close: 'Close', confirm: 'Confirm', refresh: 'Refresh'
  },
  websites: { title: 'Websites', subtitle: 'Manage domains, SSL and PHP settings.', add_new: 'Add Website', domain: 'Domain', php_version: 'PHP Version', ssl: 'SSL Certificate', ssl_active: 'SSL Active', ssl_none: 'No SSL', disk_usage: 'Disk Usage', quota: 'Quota', manage: 'Manage', issue_ssl: 'Issue SSL', delete_site: 'Delete Site', add_modal_title: 'New Website', add_success: 'Website created successfully', delete_success: 'Website deleted successfully', ssl_success: 'SSL certificate issued successfully', all_php: 'All PHP Versions' },
  users: { title: 'User Management', subtitle: 'Manage all clients and resellers on the system', add_new: 'New User', username: 'Username', email: 'Email', password: 'Password', role: 'Role', role_user: 'User', role_reseller: 'Reseller', role_admin: 'Admin', package: 'Package', sites: 'Sites', login_as: 'Login As', add_success: 'User created', delete_success: 'User deleted', add_modal_title: 'Create New User', confirm_delete: 'Are you sure you want to delete this user?' },
  packages: { title: 'Package Management', subtitle: 'Manage hosting and reseller packages', add_new: 'New Package', plan_name: 'Package Name', plan_type: 'Package Type', disk: 'Disk', bandwidth: 'Bandwidth', domains: 'Domains', databases: 'Databases', emails: 'Emails', cpu_limit: 'CPU Limit', ram_limit: 'RAM Limit', io_limit: 'I/O Limit', type_hosting: 'Hosting Plan', type_reseller: 'Reseller Plan', unlimited: 'Unlimited', edit: 'Edit Package', add_success: 'Package created', delete_success: 'Package deleted', update_success: 'Package updated' },
  databases: { title: 'Databases', subtitle: 'Manage your MariaDB and PostgreSQL databases', add_new: 'Create Database', db_name: 'Database Name', db_user: 'User', db_pass: 'Password', engine: 'Engine', size: 'Size', drop_confirm: 'Are you sure you want to drop this database?', add_success: 'Database created', delete_success: 'Database deleted', total: 'Total', users: 'Users' },
  emails: { title: 'Email Accounts', subtitle: 'Manage email accounts via Stalwart Mail Server', add_new: 'Create Email', address: 'Email Address', domain: 'Domain', quota: 'Quota (MB)', add_modal_title: 'New Email Account', add_success: 'Email account created', delete_success: 'Email account deleted', confirm_delete: 'Are you sure you want to delete this email account?' },
  dns: { title: 'DNS Management', subtitle: 'Manage your domain records via PowerDNS', add_zone: 'New DNS Zone', add_record: 'Add Record', zone: 'Zone', record_type: 'Record Type', record_name: 'Name', record_value: 'Value', record_ttl: 'TTL', add_zone_success: 'DNS Zone created', add_record_success: 'DNS record added', manage_records: 'Manage Records', default_ns: 'Default NS' },
  filemanager: { title: 'File Manager', subtitle: 'Manage server files', new_file: 'New File', new_folder: 'New Folder', upload: 'Upload', save: 'Save', rename: 'Rename', delete: 'Delete', download: 'Download', edit: 'Edit', file_name: 'File Name', folder_name: 'Folder Name', save_success: 'File saved', delete_success: 'Deleted', upload_success: 'Upload complete', confirm_delete: 'Are you sure you want to delete this?', name: 'Name', size: 'Size', permissions: 'Permissions', modified: 'Modified', actions: 'Actions', compress: 'Compress', trash: 'Move to Trash', empty_dir: 'Directory is empty', drag_drop: 'Drag and drop files here or click to browse', compress_title: 'Compress Files', extract: 'Extract', messages: { read_error: 'Read error', rename_success: 'Renamed successfully', rename_error: 'Rename failed', trash_success: 'Moved to trash', trash_error: 'Failed to move to trash', trash_confirm: 'Are you sure you want to move selected items to trash?', trash_partial_error: 'Failed to move some items to trash', delete_permanent_confirm: 'Permanently delete?', delete_permanent_success: 'Item permanently deleted', delete_permanent_error: 'Permanent delete failed', delete_selected_permanent_confirm: 'Permanently delete selected items? This cannot be undone.', delete_selected_permanent_success: 'Selected items permanently deleted', delete_selected_permanent_error: 'Permanent delete failed for one or more items', compress_success: 'Archive created', compress_error: 'Archiving failed', extract_success: 'Archive extracted', extract_error: 'Extraction failed', create_file_success: 'File created', create_file_error: 'Failed to create file', create_folder_success: 'Folder created', create_folder_error: 'Failed to create folder' } },
  php: { title: 'PHP Management', subtitle: 'PHP versions and settings', versions_tab: 'Versions', sites_tab: 'Site Assignments', extensions_tab: 'Extensions', ini_tab: 'php.ini', installed: 'Installed', not_installed: 'Not Installed', eol: 'EOL', install: 'Install', remove: 'Remove', restart: 'Restart', install_success: 'PHP installed', remove_success: 'PHP removed', save_ini_success: 'php.ini saved', supported: 'Supported', domain: 'Domain', current_php: 'Current PHP', change_php: 'Change', site_not_found: 'No websites found', read_ini: 'Read', messages: { load_failed: 'PHP data could not be loaded.', installed: 'PHP {version} installed.', install_failed: 'PHP installation failed.', removed: 'PHP {version} removed.', remove_failed: 'PHP removal failed.', restarted: 'PHP {version} restarted.', restart_failed: 'PHP restart failed.', site_updated: 'PHP updated for {domain}.', site_update_failed: 'Website PHP assignment failed.', ini_read_failed: 'php.ini could not be read.', ini_save_failed: 'php.ini could not be saved.' } },
  server_status: { title: 'Server Status', subtitle: 'Server metrics, services and processes', cpu: 'CPU Usage', ram: 'RAM Usage', disk: 'Disk Usage', uptime: 'Uptime', services_tab: 'Services', processes_tab: 'Processes', network_tab: 'Network', start: 'Start', stop: 'Stop', restart: 'Restart', running: 'Running', starting: 'Starting', failed: 'Failed', stopped: 'Stopped', kill_process: 'Kill', refresh: 'Refresh', user: 'User', command: 'Command', action: 'Action', load_avg: 'Load: {value}', messages: { service_done: '{name} {action} completed', service_failed: 'Service action failed', process_killed: 'PID {pid} terminated', process_failed: 'Process termination failed', updated: 'Data refreshed' } },
  cloudflare: { title: 'CloudFlare', api_key: 'API Key', email: 'Email', connect: 'Connect', zones_tab: 'Zones', dns_tab: 'DNS', ssl_tab: 'SSL/TLS', cache_tab: 'Cache', security_tab: 'Security', purge_cache: 'Purge Cache', dev_mode: 'Developer Mode', connection_success: 'CloudFlare connected successfully' },
  docker: { title: 'Docker', manager_title: 'Docker Manager', apps_title: 'Docker Apps', containers_tab: 'Containers', images_tab: 'Images', start: 'Start', stop: 'Stop', restart: 'Restart', remove: 'Remove', pull: 'Pull', create: 'Create', running: 'Running', exited: 'Exited', install_app: 'Install', app_installed: 'Installed' },
  activity_log: { title: 'Activity Log', subtitle: 'Track all panel actions and events', user: 'User', action: 'Action', detail: 'Detail', ip: 'IP Address', timestamp: 'Time', no_data: 'No activity recorded yet', filter_user: 'Filter by user', filter_all: 'All users' },
  db_backup: { title: 'Database Backup', subtitle: 'Backup and restore your databases', create_backup: 'Create Backup', restore: 'Restore', download: 'Download', backup_history: 'Backup History', no_backups: 'No backups yet', backup_created: 'Backup created successfully', restore_confirm: 'Restore this backup? Current data will be overwritten.' },
  cms_installer: { title: 'CMS Installer', subtitle: 'One-click install for WordPress and Laravel', app_type: 'Application', domain: 'Domain', db_name: 'Database Name', db_user: 'Database User', db_pass: 'Database Password', admin_email: 'Admin Email', admin_user: 'Admin Username', admin_pass: 'Admin Password', install: 'Install', installing: 'Installing...', success: 'Installation completed successfully' },
  app_runtime: {
    title: 'App Runtime',
    subtitle: 'Node.js, Python and CMS application management',
    wordpress_manager: 'WordPress Manager',
    refresh: 'Refresh',
    running_apps: 'Running Applications',
    empty: 'No application records found.',
    tabs: { nodejs: 'Node.js', python: 'Python' },
    node: { dir_placeholder: 'Project directory', app_name_placeholder: 'App name', start_script_placeholder: 'npm start', install_deps: 'Install Deps', start: 'Start', stop: 'Stop' },
    python: { dir_placeholder: 'Project directory', app_name_placeholder: 'App name', wsgi_placeholder: 'app:app', port_placeholder: '8001', create_venv: 'Create venv', install_requirements: 'Install req', start: 'Start' },
    cms: { help_prefix: 'After installation, manage plugin, theme, backup and staging operations from the', help_suffix: 'screen.' }
  },
  dashboard: {
    na: 'N/A', trend_week: '{sign}{trend}% this week', system_load_map: 'System Load Map', refresh: 'Refresh', refreshing: 'Refreshing...', uptime: 'Uptime: {value}', load_avg: 'Load avg: {value}', sre_log: 'Autonomous SRE Log', empty_logs: 'No security or service events found yet.', service_check: 'service check', security_event: 'security event', runtime_snapshot: 'runtime snapshot', running_services: '{count} services are running', load_failed: 'Dashboard data could not be loaded.',
    stats: { active_websites: 'Active Websites', server_uptime: 'Server Uptime', databases: 'Databases', threats_blocked: 'Threats Blocked' }
  },
  log_viewer: { title: 'Log Viewer', subtitle: 'Site-based access and error log stream.', refresh: 'Refresh', domain_placeholder: 'example.com', lines_placeholder: '50', fetch: 'Fetch Logs', output: 'Log Output' },
  cron_jobs: { title: 'Cron Jobs', subtitle: 'Manage site-based scheduled tasks.', refresh: 'Refresh', create_title: 'New Cron Job', user_placeholder: 'user', schedule_placeholder: '*/5 * * * *', command_placeholder: 'php /home/site/artisan schedule:run', add: 'Add', list_title: 'Cron List', delete: 'Delete', empty: 'No cron jobs found.' },
  minio: {
    title: 'MinIO Storage', subtitle: 'Manage S3-compatible buckets and access credentials.', refresh: 'Refresh', create_bucket: 'Create Bucket', bucket_placeholder: 'bucket-name', create: 'Create', credentials: 'User Credentials', user_placeholder: 'user', generate: 'Generate', access_key: 'Access Key', secret_key: 'Secret Key', bucket_list: 'Bucket List', empty: 'No buckets found.', aws_title: 'AWS S3 Connection', aws_subtitle: 'Configure external AWS S3 bucket access in the same page.', aws_region_placeholder: 'Region (e.g. eu-central-1)', aws_bucket_placeholder: 'Bucket name', aws_secret_placeholder: 'Secret key (leave blank to keep existing)', aws_endpoint_placeholder: 'Endpoint (optional, e.g. s3.eu-central-1.amazonaws.com)', aws_use_path_style: 'Use path-style requests', aws_secret_kept: 'Existing secret key is kept unless you enter a new one.', aws_save: 'Save AWS Config', aws_test: 'Test Connection', aws_saved: 'AWS S3 configuration saved.', aws_save_failed: 'AWS S3 configuration could not be saved.', aws_test_ok: 'AWS S3 connection successful.', aws_test_failed: 'AWS S3 connection failed.'
  },
  federated: { title: 'Federated Nodes', subtitle: 'Multi-server federation over WireGuard.', refresh: 'Refresh', mode_status: 'Mode: {mode} / Role: {role}', add_node: 'Add Node', node_name_placeholder: 'node-eu-1', ip_placeholder: '10.0.0.2/32', pubkey_placeholder: 'wireguard public key', passive_notice: 'This node is in passive mode; adding new peers is disabled by active-passive policy.', connected_nodes: 'Connected Nodes', empty: 'No nodes found.', roles: { primary: 'primary', passive: 'passive' } },
  ols_tuning: { title: 'OLS Tuning', subtitle: 'Manage OpenLiteSpeed global tuning parameters.', refresh: 'Refresh', save: 'Save', save_apply: 'Save + Apply', fields: { max_connections: 'Max Connections', max_ssl_connections: 'Max SSL Connections', conn_timeout_secs: 'Connection Timeout (sec)', keep_alive_timeout_secs: 'KeepAlive Timeout (sec)', max_keep_alive_requests: 'Max KeepAlive Requests', static_cache_max_age_secs: 'Static Cache Max Age (sec)' }, flags: { gzip_compression: 'Gzip Compression', static_cache_enabled: 'Static Cache' }, messages: { load_failed: 'OLS tuning data could not be loaded.', saved: 'OLS tuning settings saved.', save_failed: 'OLS tuning settings could not be saved.', applied: 'OLS tuning applied.', apply_failed: 'OLS tuning could not be applied.' } },
  panel_port: {
    title: 'Panel Control', subtitle: 'Manage panel port and reverse domain settings.', tabs: { port: 'Port Settings', reverse_domain: 'Reverse Domain' }, notice_title: 'Important Notice', notice_body: 'After changing the port, reconnect using the new URL. Keep firewall access enabled for the selected port.', current_config: 'Current Configuration', current_port: 'Current panel port', new_port: 'New Port Number', port_placeholder: '8090', valid_range: 'Valid range: 1 - 65535. Common ports: 8090, 8443, 7080.', open_firewall: 'Try to open firewall for the new panel port automatically', changing: 'Changing...', change: 'Change Port', reconnect_url: 'Reconnect URL', warnings: 'Warnings', firewall_actions: 'Firewall Actions',
    reverse: { title: 'Single-domain reverse gateway settings.', subtitle: 'Configure reverse domain mode and keep OpenLiteSpeed upstream in sync with gateway port.', enabled: 'Enable single-domain reverse mode', domain: 'Reverse Domain', domain_placeholder: 'panel.example.com', vhost_conf_path: 'OLS Vhost Config Path', vhost_conf_placeholder: '/usr/local/lsws/conf/vhosts/Example/vhconf.conf', current_upstream: 'Current gateway upstream', save: 'Save Reverse Domain', saving: 'Saving...', warnings: 'Reverse Domain Warnings', messages: { load_failed: 'Reverse domain settings could not be loaded.', domain_required: 'Domain is required when reverse domain mode is enabled.', invalid_domain: 'Please enter a valid domain name.', update_failed: 'Reverse domain settings could not be updated.', updated: 'Reverse domain settings updated.', updated_synced: 'Reverse domain settings updated and OLS upstream synced.' } },
    messages: { load_failed: 'Panel port information could not be loaded.', invalid_port: 'Port must be in the 1-65535 range.', update_failed: 'Panel port could not be updated.', restart_scheduled: 'Gateway restart scheduled.', updated: 'Panel port updated to {port}.{restartNote}', network_reconnect: 'Connection was interrupted. The gateway may have restarted, reconnect on the new port: {url}' }
  },
  panel_update: { title: 'Panel Update', subtitle: 'Check release status and apply updates to this server.', channel: 'Release Channel', check_now: 'Check Now', checking: 'Checking...', update_now: 'Update', updating: 'Updating...', current_version: 'Current Version', latest_release: 'Latest Release', source: 'Source', not_checked: 'Not checked yet', last_checked: 'Last checked', up_to_date: 'This server is currently running the configured panel version.', update_available: 'A newer GitHub release is available for this panel.', view_release: 'View GitHub release', warnings: 'Update Warnings', steps: 'Update Steps', badges: { update_available: 'Update Available', up_to_date: 'Up to Date' }, messages: { load_failed: 'Update status could not be loaded.', apply_failed: 'Panel update could not be applied.', started: 'Panel update started in background.', in_progress: 'Panel update is running in background...', in_progress_hint: 'Do not close this page. Build and service restart may take a few minutes.', applied: 'Panel update completed.' } },
  locale: { label: 'Language', select: 'Select language', options: { tr: 'Turkce', en: 'English', de: 'Deutsch', es: 'Espanol', fr: 'Francais', id: 'Bahasa Indonesia' } },
  login: { title: 'Sign In to AuraPanel', subtitle: 'Use the administrator account created during installation.', email_label: 'Administrator email', email_placeholder: "admin{'@'}server.com", password_label: 'Administrator password', password_placeholder: 'Enter your password', twofa_label: 'Verification code', twofa_placeholder: '123456', remember_me: 'Remember this device', submit: 'Sign In', submitting: 'Signing in...', error_default: 'We could not complete the sign-in request.', hint: 'OpenLiteSpeed WebAdmin credentials are separate from AuraPanel panel credentials.', footer_tagline: 'Secure Hosting Control Plane', footer_credit: 'Built by Mkoyazilim' },
  auth_messages: { welcome_title: 'Welcome', welcome_message: 'Signed in as {email}', login_error: 'Sign in failed. Please verify your credentials.', signed_out_title: 'Signed Out', signed_out_message: 'Your session was closed securely.' },
  api_messages: { unknown_error: 'Unknown API error', session_expired: 'Session expired', session_ended_title: 'Session Ended', session_ended_message: 'Your session expired. Please sign in again.', network_error: 'Network Error', api_error_title: 'API Error - {status}' },
  layout: { toggle_all_open: 'Open All', toggle_all_close: 'Close All', toggle_all_label: 'Menu Groups', groups: { hosting: 'Hosting', web_apps: 'Web & Apps', data_access: 'Data & Access', security_logs: 'Security & Logs', devops: 'Developer', system: 'System', ftp_sftp: 'FTP / SFTP', backups: 'Backups', logs: 'Logs' }, links: { reseller_acl: 'Reseller & ACL', ssl_manage: 'SSL Management', ssl_hostname: 'Hostname SSL', ssl_mail: 'Mail Server SSL', wordpress_manager: 'WordPress Manager', app_runtime: 'App Runtime', file_manager: 'File Manager', terminal: 'Web Terminal', file_backups: 'File Backups', overview: 'Overview', firewall: 'Firewall', ssh_keys: 'SSH Settings', activity_log: 'Activity Log', log_viewer: 'Log Viewer', image_manager: 'Image Management', container_manager: 'Container Management', create_container: 'Create Container', app_store: 'App Store', installed_apps: 'Installed Apps', docker_packages: 'Docker Packages', cron_jobs: 'Cron Jobs', panel_port: 'Panel Control', ml_waf: 'ML-WAF', ddos: 'DDoS Guard', totp: '2FA (TOTP)', hardening: 'Hardening' }, labels: { manager: 'Manager', apps: 'Apps' }, notifications: { title: 'Notifications', unread: '{count} unread', mark_all_read: 'Mark all as read', clear: 'Clear', empty: 'No notifications yet.', new: 'NEW' }, user_menu: { secure_logout: 'Secure Logout' }, footer: { zero_trust: 'Zero-Trust Active', server_load: 'Server Load' }, command_palette: { placeholder: 'Quick jump with Ctrl+K... (example: dns, security, logs)' } },
  notifications: { default_title: 'Notification' },
  routes: { Dashboard: 'Dashboard', Websites: 'Websites', WebsiteManage: 'Website Manager', Packages: 'Packages', Users: 'Users', Databases: 'Databases', Emails: 'Emails', FTP: 'FTP', SFTP: 'SFTP', DNS: 'DNS', SSL: 'SSL', Security: 'Security', AppRuntime: 'App Runtime', WordPressManager: 'WordPress Manager', MinIO: 'MinIO', CronJobs: 'Cron Jobs', LogViewer: 'Log Viewer', Federated: 'Federated', FileManager: 'File Manager', Terminal: 'Web Terminal', PHP: 'PHP Management', ServerStatus: 'Server Status', PanelPort: 'Panel Control', Backups: 'Backups', OlsTuning: 'OLS Tuning', Reseller: 'Reseller & ACL', ActivityLog: 'Activity Log', DbBackup: 'DB Backup', 'Docker Images': 'Docker Images', 'Docker Containers': 'Docker Containers', 'Docker Create': 'Create Container', 'Docker App Store': 'Docker App Store', 'Docker Installed Apps': 'Installed Docker Apps', 'Docker Packages': 'Docker Packages', CloudFlare: 'CloudFlare' }
}

const baseTr = deepMerge(baseEn, {
  menu: { dashboard: 'Ana Sayfa', websites: 'Web Siteleri', packages: 'Paketler', users: 'Kullanıcılar', databases: 'Veritabanlari', emails: 'E-Posta', dns: 'DNS Yönetimi', security: 'Güvenlik', docker_manager: 'Docker Yönetimi', docker_apps: 'Docker Uygulamalari', filemanager: 'Dosya Yöneticisi', php: 'PHP Yönetimi', server_status: 'Sunucu Durumu', reseller: 'Bayi Yönetimi' },
  common: { save: 'Kaydet', cancel: 'İptal', delete: 'Sil', edit: 'Düzenle', create: 'Oluştur', add: 'Ekle', confirm_delete: 'Bu kaydı silmek istediğinize emin misiniz?', loading: 'Yükleniyor...', error: 'Bir hata oluştu', success: 'İşlem başarılı', search: 'Ara...', actions: 'İşlemler', status: 'Durum', active: 'Aktif', inactive: 'Pasif', name: 'Ad', password: 'Şifre', no_data: 'Kayıt bulunamadı', close: 'Kapat', confirm: 'Onayla', refresh: 'Yenile' },
  login: { title: "AuraPanel'e Giris Yapin", subtitle: 'Kurulum sirasinda oluşturulan yonetici hesabi ile devam edin.', email_label: 'Yönetici E-Postasi', email_placeholder: "admin{'@'}server.com", password_label: 'Yönetici Şifresi', password_placeholder: 'Şifrenizi girin', twofa_label: 'Doğrulama Kodu', twofa_placeholder: '123456', remember_me: 'Bu cihazda oturumu hatirla', submit: 'Giris Yap', submitting: 'Giris yapiliyor...', error_default: 'Giris istegi tamamlanamadi.', hint: 'OpenLiteSpeed WebAdmin bilgileri AuraPanel panel hesabindan ayridir.', footer_tagline: 'Güvenli Hosting Kontrol Duzlemi', footer_credit: 'Mkoyazilim tarafindan gelistirildi' },
  locale: { label: 'Dil', select: 'Dil secin', options: { tr: 'Turkce', en: 'English', de: 'Deutsch', es: 'Espanol', fr: 'Francais', id: 'Bahasa Indonesia' } }
})

const baseId = deepMerge(baseEn, {
  menu: { dashboard: 'Dasbor', websites: 'Situs Web', packages: 'Paket', users: 'Pengguna', databases: 'Basis Data', emails: 'Email', dns: 'Manajemen DNS', security: 'Keamanan', docker_manager: 'Manajer Docker', docker_apps: 'Aplikasi Docker', filemanager: 'Pengelola Berkas', php: 'Manajemen PHP', server_status: 'Status Server', reseller: 'Manajemen Reseller' },
  common: { save: 'Simpan', cancel: 'Batal', delete: 'Hapus', edit: 'Ubah', create: 'Buat', add: 'Tambah', confirm_delete: 'Apakah Anda yakin ingin menghapus ini?', loading: 'Memuat...', error: 'Terjadi kesalahan', success: 'Operasi berhasil', search: 'Cari...', actions: 'Tindakan', status: 'Status', active: 'Aktif', inactive: 'Tidak Aktif', name: 'Nama', email: 'Email', password: 'Kata Sandi', no_data: 'Data tidak ditemukan', close: 'Tutup', confirm: 'Konfirmasi', refresh: 'Segarkan' },
  login: { title: 'Masuk ke AuraPanel', subtitle: 'Gunakan akun administrator yang dibuat saat instalasi.', email_label: 'Email administrator', email_placeholder: "admin{'@'}server.com", password_label: 'Kata sandi administrator', password_placeholder: 'Masukkan kata sandi Anda', twofa_label: 'Kode verifikasi', twofa_placeholder: '123456', remember_me: 'Ingat perangkat ini', submit: 'Masuk', submitting: 'Masuk...', error_default: 'Kami tidak dapat menyelesaikan permintaan masuk.', hint: 'Kredensial WebAdmin OpenLiteSpeed terpisah dari kredensial panel AuraPanel.', footer_tagline: 'Bidang Kontrol Hosting Aman', footer_credit: 'Dibuat oleh Mkoyazilim' },
  locale: { label: 'Bahasa', select: 'Pilih bahasa', options: { tr: 'Turkce', en: 'English', de: 'Deutsch', es: 'Espanol', fr: 'Francais', id: 'Bahasa Indonesia' } }
})

const en = deepMerge(deepMerge(baseEn, enJson), extraEn)
const tr = deepMerge(en, deepMerge(deepMerge(baseTr, trJson), extraTr))
const id = deepMerge(en, deepMerge(deepMerge(baseId, idJson), extraId))

const de = deepMerge(en, { common: { active: 'Aktiv', inactive: 'Inaktiv' }, locale: { label: 'Sprache', select: 'Sprache wahlen' } })
const es = deepMerge(en, { common: { active: 'Activo', inactive: 'Inactivo' }, locale: { label: 'Idioma', select: 'Seleccionar idioma' } })
const fr = deepMerge(en, { common: { active: 'Actif', inactive: 'Inactif' }, locale: { label: 'Langue', select: 'Choisir la langue' } })

export const messages = { en, tr, id, de, es, fr }
export const supportedLocales = ['tr', 'en', 'id', 'de', 'es', 'fr']
export const rtlLocales = []
